/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProfileId = IDL.Nat;
export const Category = IDL.Variant({
  'social' : IDL.Null,
  'other' : IDL.Null,
  'entertainment' : IDL.Null,
  'gaming' : IDL.Null,
  'educational' : IDL.Null,
});
export const Recommendation = IDL.Variant({
  'wellbeing' : IDL.Null,
  'content' : IDL.Null,
  'screen_time' : IDL.Null,
  'social' : IDL.Null,
  'financial' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BullyingAlert = IDL.Record({
  'id' : ProfileId,
  'status' : IDL.Variant({
    'new' : IDL.Null,
    'reviewed' : IDL.Null,
    'dismissed' : IDL.Null,
  }),
  'childId' : ProfileId,
  'platform' : IDL.Text,
  'snippet' : IDL.Text,
  'timestamp' : Time,
  'severity' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChildProfile = IDL.Record({
  'id' : ProfileId,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'avatarUrl' : IDL.Text,
  'deviceName' : IDL.Text,
  'parentId' : IDL.Principal,
});
export const LocationRecord = IDL.Record({
  'id' : ProfileId,
  'latitude' : IDL.Float64,
  'childId' : ProfileId,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'timestamp' : Time,
});
export const DashboardSummary = IDL.Record({
  'todayScreenTime' : IDL.Nat,
  'todaySpendingTotal' : IDL.Nat,
  'latestLocation' : IDL.Opt(LocationRecord),
  'unreadAlertsCount' : IDL.Nat,
  'unreadRecommendationsCount' : IDL.Nat,
});
export const SafeZone = IDL.Record({
  'id' : ProfileId,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'childId' : ProfileId,
  'isActive' : IDL.Bool,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'radius' : IDL.Nat,
});
export const ScreenTimeRecord = IDL.Record({
  'id' : ProfileId,
  'appName' : IDL.Text,
  'date' : IDL.Text,
  'childId' : ProfileId,
  'durationMinutes' : IDL.Nat,
  'category' : Category,
});
export const ParentSettings = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'alertThreshold' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'weeklyReportEnabled' : IDL.Bool,
  'parentId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBullyingAlert' : IDL.Func(
      [
        ProfileId,
        IDL.Text,
        IDL.Variant({
          'low' : IDL.Null,
          'high' : IDL.Null,
          'medium' : IDL.Null,
        }),
        IDL.Text,
      ],
      [ProfileId],
      [],
    ),
  'addChild' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [ProfileId],
      [],
    ),
  'addContent' : IDL.Func(
      [ProfileId, IDL.Text, IDL.Text, Category, IDL.Nat, IDL.Bool],
      [ProfileId],
      [],
    ),
  'addLocation' : IDL.Func(
      [ProfileId, IDL.Float64, IDL.Float64, IDL.Text],
      [ProfileId],
      [],
    ),
  'addRecommendation' : IDL.Func(
      [ProfileId, Recommendation, IDL.Text, IDL.Nat],
      [ProfileId],
      [],
    ),
  'addSafeZone' : IDL.Func(
      [
        ProfileId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
      ],
      [ProfileId],
      [],
    ),
  'addScreenTime' : IDL.Func(
      [ProfileId, IDL.Text, Category, IDL.Nat, IDL.Text],
      [ProfileId],
      [],
    ),
  'addSpending' : IDL.Func(
      [ProfileId, IDL.Nat, IDL.Text, IDL.Text],
      [ProfileId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChild' : IDL.Func([ProfileId], [], []),
  'deleteSafeZone' : IDL.Func([ProfileId], [], []),
  'getAlertsByChild' : IDL.Func(
      [ProfileId],
      [IDL.Vec(BullyingAlert)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChild' : IDL.Func([ProfileId], [ChildProfile], ['query']),
  'getChildren' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
  'getDashboardSummary' : IDL.Func([ProfileId], [DashboardSummary], ['query']),
  'getLatestLocation' : IDL.Func(
      [ProfileId],
      [IDL.Opt(LocationRecord)],
      ['query'],
    ),
  'getLocationHistory' : IDL.Func(
      [ProfileId],
      [IDL.Vec(LocationRecord)],
      ['query'],
    ),
  'getSafeZones' : IDL.Func([ProfileId], [IDL.Vec(SafeZone)], ['query']),
  'getScreenTimeByDate' : IDL.Func(
      [ProfileId, IDL.Text],
      [IDL.Vec(ScreenTimeRecord)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [ParentSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRecommendationRead' : IDL.Func([ProfileId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'updateAlertStatus' : IDL.Func(
      [
        ProfileId,
        IDL.Variant({
          'new' : IDL.Null,
          'reviewed' : IDL.Null,
          'dismissed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateChild' : IDL.Func(
      [ProfileId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSafeZone' : IDL.Func(
      [
        ProfileId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateSettings' : IDL.Func(
      [
        IDL.Bool,
        IDL.Bool,
        IDL.Variant({
          'low' : IDL.Null,
          'high' : IDL.Null,
          'medium' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProfileId = IDL.Nat;
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'other' : IDL.Null,
    'entertainment' : IDL.Null,
    'gaming' : IDL.Null,
    'educational' : IDL.Null,
  });
  const Recommendation = IDL.Variant({
    'wellbeing' : IDL.Null,
    'content' : IDL.Null,
    'screen_time' : IDL.Null,
    'social' : IDL.Null,
    'financial' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BullyingAlert = IDL.Record({
    'id' : ProfileId,
    'status' : IDL.Variant({
      'new' : IDL.Null,
      'reviewed' : IDL.Null,
      'dismissed' : IDL.Null,
    }),
    'childId' : ProfileId,
    'platform' : IDL.Text,
    'snippet' : IDL.Text,
    'timestamp' : Time,
    'severity' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChildProfile = IDL.Record({
    'id' : ProfileId,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'avatarUrl' : IDL.Text,
    'deviceName' : IDL.Text,
    'parentId' : IDL.Principal,
  });
  const LocationRecord = IDL.Record({
    'id' : ProfileId,
    'latitude' : IDL.Float64,
    'childId' : ProfileId,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'timestamp' : Time,
  });
  const DashboardSummary = IDL.Record({
    'todayScreenTime' : IDL.Nat,
    'todaySpendingTotal' : IDL.Nat,
    'latestLocation' : IDL.Opt(LocationRecord),
    'unreadAlertsCount' : IDL.Nat,
    'unreadRecommendationsCount' : IDL.Nat,
  });
  const SafeZone = IDL.Record({
    'id' : ProfileId,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'childId' : ProfileId,
    'isActive' : IDL.Bool,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'radius' : IDL.Nat,
  });
  const ScreenTimeRecord = IDL.Record({
    'id' : ProfileId,
    'appName' : IDL.Text,
    'date' : IDL.Text,
    'childId' : ProfileId,
    'durationMinutes' : IDL.Nat,
    'category' : Category,
  });
  const ParentSettings = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'alertThreshold' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'weeklyReportEnabled' : IDL.Bool,
    'parentId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBullyingAlert' : IDL.Func(
        [
          ProfileId,
          IDL.Text,
          IDL.Variant({
            'low' : IDL.Null,
            'high' : IDL.Null,
            'medium' : IDL.Null,
          }),
          IDL.Text,
        ],
        [ProfileId],
        [],
      ),
    'addChild' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [ProfileId],
        [],
      ),
    'addContent' : IDL.Func(
        [ProfileId, IDL.Text, IDL.Text, Category, IDL.Nat, IDL.Bool],
        [ProfileId],
        [],
      ),
    'addLocation' : IDL.Func(
        [ProfileId, IDL.Float64, IDL.Float64, IDL.Text],
        [ProfileId],
        [],
      ),
    'addRecommendation' : IDL.Func(
        [ProfileId, Recommendation, IDL.Text, IDL.Nat],
        [ProfileId],
        [],
      ),
    'addSafeZone' : IDL.Func(
        [
          ProfileId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
        ],
        [ProfileId],
        [],
      ),
    'addScreenTime' : IDL.Func(
        [ProfileId, IDL.Text, Category, IDL.Nat, IDL.Text],
        [ProfileId],
        [],
      ),
    'addSpending' : IDL.Func(
        [ProfileId, IDL.Nat, IDL.Text, IDL.Text],
        [ProfileId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChild' : IDL.Func([ProfileId], [], []),
    'deleteSafeZone' : IDL.Func([ProfileId], [], []),
    'getAlertsByChild' : IDL.Func(
        [ProfileId],
        [IDL.Vec(BullyingAlert)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChild' : IDL.Func([ProfileId], [ChildProfile], ['query']),
    'getChildren' : IDL.Func([], [IDL.Vec(ChildProfile)], ['query']),
    'getDashboardSummary' : IDL.Func(
        [ProfileId],
        [DashboardSummary],
        ['query'],
      ),
    'getLatestLocation' : IDL.Func(
        [ProfileId],
        [IDL.Opt(LocationRecord)],
        ['query'],
      ),
    'getLocationHistory' : IDL.Func(
        [ProfileId],
        [IDL.Vec(LocationRecord)],
        ['query'],
      ),
    'getSafeZones' : IDL.Func([ProfileId], [IDL.Vec(SafeZone)], ['query']),
    'getScreenTimeByDate' : IDL.Func(
        [ProfileId, IDL.Text],
        [IDL.Vec(ScreenTimeRecord)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [ParentSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRecommendationRead' : IDL.Func([ProfileId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'updateAlertStatus' : IDL.Func(
        [
          ProfileId,
          IDL.Variant({
            'new' : IDL.Null,
            'reviewed' : IDL.Null,
            'dismissed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateChild' : IDL.Func(
        [ProfileId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSafeZone' : IDL.Func(
        [
          ProfileId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateSettings' : IDL.Func(
        [
          IDL.Bool,
          IDL.Bool,
          IDL.Variant({
            'low' : IDL.Null,
            'high' : IDL.Null,
            'medium' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };