/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BullyingAlert {
  'id' : ProfileId,
  'status' : { 'new' : null } |
    { 'reviewed' : null } |
    { 'dismissed' : null },
  'childId' : ProfileId,
  'platform' : string,
  'snippet' : string,
  'timestamp' : Time,
  'severity' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
}
export type Category = { 'social' : null } |
  { 'other' : null } |
  { 'entertainment' : null } |
  { 'gaming' : null } |
  { 'educational' : null };
export interface ChildProfile {
  'id' : ProfileId,
  'age' : bigint,
  'name' : string,
  'createdAt' : Time,
  'avatarUrl' : string,
  'deviceName' : string,
  'parentId' : Principal,
}
export interface DashboardSummary {
  'todayScreenTime' : bigint,
  'todaySpendingTotal' : bigint,
  'latestLocation' : [] | [LocationRecord],
  'unreadAlertsCount' : bigint,
  'unreadRecommendationsCount' : bigint,
}
export interface LocationRecord {
  'id' : ProfileId,
  'latitude' : number,
  'childId' : ProfileId,
  'longitude' : number,
  'address' : string,
  'timestamp' : Time,
}
export interface ParentSettings {
  'notificationsEnabled' : boolean,
  'alertThreshold' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
  'weeklyReportEnabled' : boolean,
  'parentId' : Principal,
}
export type ProfileId = bigint;
export type Recommendation = { 'wellbeing' : null } |
  { 'content' : null } |
  { 'screen_time' : null } |
  { 'social' : null } |
  { 'financial' : null };
export interface SafeZone {
  'id' : ProfileId,
  'latitude' : number,
  'name' : string,
  'childId' : ProfileId,
  'isActive' : boolean,
  'longitude' : number,
  'address' : string,
  'radius' : bigint,
}
export interface ScreenTimeRecord {
  'id' : ProfileId,
  'appName' : string,
  'date' : string,
  'childId' : ProfileId,
  'durationMinutes' : bigint,
  'category' : Category,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBullyingAlert' : ActorMethod<
    [
      ProfileId,
      string,
      { 'low' : null } |
        { 'high' : null } |
        { 'medium' : null },
      string,
    ],
    ProfileId
  >,
  'addChild' : ActorMethod<[string, bigint, string, string], ProfileId>,
  'addContent' : ActorMethod<
    [ProfileId, string, string, Category, bigint, boolean],
    ProfileId
  >,
  'addLocation' : ActorMethod<[ProfileId, number, number, string], ProfileId>,
  'addRecommendation' : ActorMethod<
    [ProfileId, Recommendation, string, bigint],
    ProfileId
  >,
  'addSafeZone' : ActorMethod<
    [ProfileId, string, string, number, number, bigint, boolean],
    ProfileId
  >,
  'addScreenTime' : ActorMethod<
    [ProfileId, string, Category, bigint, string],
    ProfileId
  >,
  'addSpending' : ActorMethod<[ProfileId, bigint, string, string], ProfileId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChild' : ActorMethod<[ProfileId], undefined>,
  'deleteSafeZone' : ActorMethod<[ProfileId], undefined>,
  'getAlertsByChild' : ActorMethod<[ProfileId], Array<BullyingAlert>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChild' : ActorMethod<[ProfileId], ChildProfile>,
  'getChildren' : ActorMethod<[], Array<ChildProfile>>,
  'getDashboardSummary' : ActorMethod<[ProfileId], DashboardSummary>,
  'getLatestLocation' : ActorMethod<[ProfileId], [] | [LocationRecord]>,
  'getLocationHistory' : ActorMethod<[ProfileId], Array<LocationRecord>>,
  'getSafeZones' : ActorMethod<[ProfileId], Array<SafeZone>>,
  'getScreenTimeByDate' : ActorMethod<
    [ProfileId, string],
    Array<ScreenTimeRecord>
  >,
  'getSettings' : ActorMethod<[], ParentSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRecommendationRead' : ActorMethod<[ProfileId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'updateAlertStatus' : ActorMethod<
    [
      ProfileId,
      { 'new' : null } |
        { 'reviewed' : null } |
        { 'dismissed' : null },
    ],
    undefined
  >,
  'updateChild' : ActorMethod<
    [ProfileId, string, bigint, string, string],
    undefined
  >,
  'updateSafeZone' : ActorMethod<
    [ProfileId, string, string, number, number, bigint, boolean],
    undefined
  >,
  'updateSettings' : ActorMethod<
    [
      boolean,
      boolean,
      { 'low' : null } |
        { 'high' : null } |
        { 'medium' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];