/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ParentSettings {
    notificationsEnabled: boolean;
    alertThreshold: Variant_low_high_medium;
    weeklyReportEnabled: boolean;
    parentId: Principal;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ScreenTimeRecord {
    id: ProfileId;
    appName: string;
    date: string;
    childId: ProfileId;
    durationMinutes: bigint;
    category: Category;
}
export type ProfileId = bigint;
export interface ParentAccount {
    createdAt: Time;
    plan: SubscriptionPlan;
    email: string;
    passwordHash: string;
}
export interface DashboardSummary {
    todayScreenTime: bigint;
    todaySpendingTotal: bigint;
    latestLocation?: LocationRecord;
    unreadAlertsCount: bigint;
    unreadRecommendationsCount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ChildProfile {
    id: ProfileId;
    age: bigint;
    name: string;
    createdAt: Time;
    avatarUrl: string;
    deviceName: string;
    parentId: Principal;
}
export interface LocationRecord {
    id: ProfileId;
    latitude: number;
    childId: ProfileId;
    longitude: number;
    address: string;
    timestamp: Time;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SafeZone {
    id: ProfileId;
    latitude: number;
    name: string;
    childId: ProfileId;
    isActive: boolean;
    longitude: number;
    address: string;
    radius: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface BullyingAlert {
    id: ProfileId;
    status: Variant_new_reviewed_dismissed;
    childId: ProfileId;
    platform: string;
    snippet: string;
    timestamp: Time;
    severity: Variant_low_high_medium;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    social = "social",
    other = "other",
    entertainment = "entertainment",
    gaming = "gaming",
    educational = "educational"
}
export enum Recommendation {
    wellbeing = "wellbeing",
    content = "content",
    screen_time = "screen_time",
    social = "social",
    financial = "financial"
}
export enum SubscriptionPlan {
    free = "free",
    guardian_pro = "guardian_pro",
    family = "family"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Variant_new_reviewed_dismissed {
    new_ = "new",
    reviewed = "reviewed",
    dismissed = "dismissed"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBullyingAlert(childId: ProfileId, platform: string, severity: Variant_low_high_medium, snippet: string): Promise<ProfileId>;
    addChild(name: string, age: bigint, deviceName: string, avatarUrl: string): Promise<ProfileId>;
    addContent(childId: ProfileId, url: string, title: string, category: Category, riskScore: bigint, flagged: boolean): Promise<ProfileId>;
    addLocation(childId: ProfileId, latitude: number, longitude: number, address: string): Promise<ProfileId>;
    addRecommendation(childId: ProfileId, tipType: Recommendation, content: string, priority: bigint): Promise<ProfileId>;
    addSafeZone(childId: ProfileId, name: string, address: string, latitude: number, longitude: number, radius: bigint, isActive: boolean): Promise<ProfileId>;
    addScreenTime(childId: ProfileId, appName: string, category: Category, durationMinutes: bigint, date: string): Promise<ProfileId>;
    addSpending(childId: ProfileId, amount: bigint, category: string, merchant: string): Promise<ProfileId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createSubscriptionCheckoutSession(plan: SubscriptionPlan): Promise<string>;
    deleteChild(id: ProfileId): Promise<void>;
    deleteSafeZone(id: ProfileId): Promise<void>;
    getAlertsByChild(childId: ProfileId): Promise<Array<BullyingAlert>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChild(id: ProfileId): Promise<ChildProfile>;
    getChildren(): Promise<Array<ChildProfile>>;
    getDashboardSummary(childId: ProfileId): Promise<DashboardSummary>;
    getLatestLocation(childId: ProfileId): Promise<LocationRecord | null>;
    getLocationHistory(childId: ProfileId): Promise<Array<LocationRecord>>;
    getParentAccount(): Promise<ParentAccount>;
    getSafeZones(childId: ProfileId): Promise<Array<SafeZone>>;
    getScreenTimeByDate(childId: ProfileId, date: string): Promise<Array<ScreenTimeRecord>>;
    getSettings(): Promise<ParentSettings>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionPlan(): Promise<SubscriptionPlan>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleStripeWebhook(sessionId: string, plan: SubscriptionPlan): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isFeatureUnlocked(feature: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    loginParent(email: string, passwordHash: string): Promise<boolean>;
    markRecommendationRead(id: ProfileId): Promise<void>;
    registerParent(email: string, passwordHash: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAlertStatus(id: ProfileId, status: Variant_new_reviewed_dismissed): Promise<void>;
    updateChild(id: ProfileId, name: string, age: bigint, deviceName: string, avatarUrl: string): Promise<void>;
    updateParentEmail(email: string): Promise<void>;
    updateParentPassword(passwordHash: string): Promise<void>;
    updateSafeZone(id: ProfileId, name: string, address: string, latitude: number, longitude: number, radius: bigint, isActive: boolean): Promise<void>;
    updateSettings(notificationsEnabled: boolean, weeklyReportEnabled: boolean, alertThreshold: Variant_low_high_medium): Promise<void>;
    updateSubscriptionPlan(plan: SubscriptionPlan): Promise<void>;
}
import type { BullyingAlert as _BullyingAlert, Category as _Category, DashboardSummary as _DashboardSummary, LocationRecord as _LocationRecord, ParentAccount as _ParentAccount, ParentSettings as _ParentSettings, ProfileId as _ProfileId, Recommendation as _Recommendation, ScreenTimeRecord as _ScreenTimeRecord, StripeSessionStatus as _StripeSessionStatus, SubscriptionPlan as _SubscriptionPlan, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBullyingAlert(arg0: ProfileId, arg1: string, arg2: Variant_low_high_medium, arg3: string): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addBullyingAlert(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBullyingAlert(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addChild(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addChild(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChild(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addContent(arg0: ProfileId, arg1: string, arg2: string, arg3: Category, arg4: bigint, arg5: boolean): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addContent(arg0, arg1, arg2, to_candid_Category_n2(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContent(arg0, arg1, arg2, to_candid_Category_n2(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addLocation(arg0: ProfileId, arg1: number, arg2: number, arg3: string): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addRecommendation(arg0: ProfileId, arg1: Recommendation, arg2: string, arg3: bigint): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecommendation(arg0, to_candid_Recommendation_n4(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecommendation(arg0, to_candid_Recommendation_n4(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addSafeZone(arg0: ProfileId, arg1: string, arg2: string, arg3: number, arg4: number, arg5: bigint, arg6: boolean): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSafeZone(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSafeZone(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addScreenTime(arg0: ProfileId, arg1: string, arg2: Category, arg3: bigint, arg4: string): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addScreenTime(arg0, arg1, to_candid_Category_n2(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScreenTime(arg0, arg1, to_candid_Category_n2(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async addSpending(arg0: ProfileId, arg1: bigint, arg2: string, arg3: string): Promise<ProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSpending(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSpending(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createSubscriptionCheckoutSession(arg0: SubscriptionPlan): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscriptionCheckoutSession(to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscriptionCheckoutSession(to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteChild(arg0: ProfileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChild(arg0);
            return result;
        }
    }
    async deleteSafeZone(arg0: ProfileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSafeZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSafeZone(arg0);
            return result;
        }
    }
    async getAlertsByChild(arg0: ProfileId): Promise<Array<BullyingAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsByChild(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsByChild(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChild(arg0: ProfileId): Promise<ChildProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChild(arg0);
            return result;
        }
    }
    async getChildren(): Promise<Array<ChildProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildren();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildren();
            return result;
        }
    }
    async getDashboardSummary(arg0: ProfileId): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary(arg0);
                return from_candid_DashboardSummary_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary(arg0);
            return from_candid_DashboardSummary_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestLocation(arg0: ProfileId): Promise<LocationRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestLocation(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestLocation(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocationHistory(arg0: ProfileId): Promise<Array<LocationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationHistory(arg0);
            return result;
        }
    }
    async getParentAccount(): Promise<ParentAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.getParentAccount();
                return from_candid_ParentAccount_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParentAccount();
            return from_candid_ParentAccount_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafeZones(arg0: ProfileId): Promise<Array<SafeZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafeZones(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafeZones(arg0);
            return result;
        }
    }
    async getScreenTimeByDate(arg0: ProfileId, arg1: string): Promise<Array<ScreenTimeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScreenTimeByDate(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScreenTimeByDate(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<ParentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_ParentSettings_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_ParentSettings_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionPlan(): Promise<SubscriptionPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionPlan();
                return from_candid_SubscriptionPlan_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionPlan();
            return from_candid_SubscriptionPlan_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleStripeWebhook(arg0: string, arg1: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleStripeWebhook(arg0, to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleStripeWebhook(arg0, to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFeatureUnlocked(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFeatureUnlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFeatureUnlocked(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async loginParent(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginParent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginParent(arg0, arg1);
            return result;
        }
    }
    async markRecommendationRead(arg0: ProfileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRecommendationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRecommendationRead(arg0);
            return result;
        }
    }
    async registerParent(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerParent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerParent(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAlertStatus(arg0: ProfileId, arg1: Variant_new_reviewed_dismissed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlertStatus(arg0, to_candid_variant_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlertStatus(arg0, to_candid_variant_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateChild(arg0: ProfileId, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChild(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChild(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateParentEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParentEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParentEmail(arg0);
            return result;
        }
    }
    async updateParentPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParentPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParentPassword(arg0);
            return result;
        }
    }
    async updateSafeZone(arg0: ProfileId, arg1: string, arg2: string, arg3: number, arg4: number, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSafeZone(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSafeZone(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSettings(arg0: boolean, arg1: boolean, arg2: Variant_low_high_medium): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSubscriptionPlan(arg0: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionPlan(to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionPlan(to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BullyingAlert_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BullyingAlert): BullyingAlert {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardSummary_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardSummary): DashboardSummary {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ParentAccount_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParentAccount): ParentAccount {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ParentSettings_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParentSettings): ParentSettings {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ScreenTimeRecord_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScreenTimeRecord): ScreenTimeRecord {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocationRecord]): LocationRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProfileId;
    status: {
        new: null;
    } | {
        reviewed: null;
    } | {
        dismissed: null;
    };
    childId: _ProfileId;
    platform: string;
    snippet: string;
    timestamp: _Time;
    severity: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
}): {
    id: ProfileId;
    status: Variant_new_reviewed_dismissed;
    childId: ProfileId;
    platform: string;
    snippet: string;
    timestamp: Time;
    severity: Variant_low_high_medium;
} {
    return {
        id: value.id,
        status: from_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        childId: value.childId,
        platform: value.platform,
        snippet: value.snippet,
        timestamp: value.timestamp,
        severity: from_candid_variant_n14(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todayScreenTime: bigint;
    todaySpendingTotal: bigint;
    latestLocation: [] | [_LocationRecord];
    unreadAlertsCount: bigint;
    unreadRecommendationsCount: bigint;
}): {
    todayScreenTime: bigint;
    todaySpendingTotal: bigint;
    latestLocation?: LocationRecord;
    unreadAlertsCount: bigint;
    unreadRecommendationsCount: bigint;
} {
    return {
        todayScreenTime: value.todayScreenTime,
        todaySpendingTotal: value.todaySpendingTotal,
        latestLocation: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.latestLocation)),
        unreadAlertsCount: value.unreadAlertsCount,
        unreadRecommendationsCount: value.unreadRecommendationsCount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Time;
    plan: _SubscriptionPlan;
    email: string;
    passwordHash: string;
}): {
    createdAt: Time;
    plan: SubscriptionPlan;
    email: string;
    passwordHash: string;
} {
    return {
        createdAt: value.createdAt,
        plan: from_candid_SubscriptionPlan_n23(_uploadFile, _downloadFile, value.plan),
        email: value.email,
        passwordHash: value.passwordHash
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProfileId;
    appName: string;
    date: string;
    childId: _ProfileId;
    durationMinutes: bigint;
    category: _Category;
}): {
    id: ProfileId;
    appName: string;
    date: string;
    childId: ProfileId;
    durationMinutes: bigint;
    category: Category;
} {
    return {
        id: value.id,
        appName: value.appName,
        date: value.date,
        childId: value.childId,
        durationMinutes: value.durationMinutes,
        category: from_candid_Category_n28(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    alertThreshold: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    weeklyReportEnabled: boolean;
    parentId: Principal;
}): {
    notificationsEnabled: boolean;
    alertThreshold: Variant_low_high_medium;
    weeklyReportEnabled: boolean;
    parentId: Principal;
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        alertThreshold: from_candid_variant_n14(_uploadFile, _downloadFile, value.alertThreshold),
        weeklyReportEnabled: value.weeklyReportEnabled,
        parentId: value.parentId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    reviewed: null;
} | {
    dismissed: null;
}): Variant_new_reviewed_dismissed {
    return "new" in value ? Variant_new_reviewed_dismissed.new : "reviewed" in value ? Variant_new_reviewed_dismissed.reviewed : "dismissed" in value ? Variant_new_reviewed_dismissed.dismissed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    guardian_pro: null;
} | {
    family: null;
}): SubscriptionPlan {
    return "free" in value ? SubscriptionPlan.free : "guardian_pro" in value ? SubscriptionPlan.guardian_pro : "family" in value ? SubscriptionPlan.family : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    gaming: null;
} | {
    educational: null;
}): Category {
    return "social" in value ? Category.social : "other" in value ? Category.other : "entertainment" in value ? Category.entertainment : "gaming" in value ? Category.gaming : "educational" in value ? Category.educational : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n34(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BullyingAlert>): Array<BullyingAlert> {
    return value.map((x)=>from_candid_BullyingAlert_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScreenTimeRecord>): Array<ScreenTimeRecord> {
    return value.map((x)=>from_candid_ScreenTimeRecord_n26(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Recommendation_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): _Recommendation {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    social: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    gaming: null;
} | {
    educational: null;
} {
    return value == Category.social ? {
        social: null
    } : value == Category.other ? {
        other: null
    } : value == Category.entertainment ? {
        entertainment: null
    } : value == Category.gaming ? {
        gaming: null
    } : value == Category.educational ? {
        educational: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_new_reviewed_dismissed): {
    new: null;
} | {
    reviewed: null;
} | {
    dismissed: null;
} {
    return value == Variant_new_reviewed_dismissed.new ? {
        new_: null
    } : value == Variant_new_reviewed_dismissed.reviewed ? {
        reviewed: null
    } : value == Variant_new_reviewed_dismissed.dismissed ? {
        dismissed: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recommendation): {
    wellbeing: null;
} | {
    content: null;
} | {
    screen_time: null;
} | {
    social: null;
} | {
    financial: null;
} {
    return value == Recommendation.wellbeing ? {
        wellbeing: null
    } : value == Recommendation.content ? {
        content: null
    } : value == Recommendation.screen_time ? {
        screen_time: null
    } : value == Recommendation.social ? {
        social: null
    } : value == Recommendation.financial ? {
        financial: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    free: null;
} | {
    guardian_pro: null;
} | {
    family: null;
} {
    return value == SubscriptionPlan.free ? {
        free: null
    } : value == SubscriptionPlan.guardian_pro ? {
        guardian_pro: null
    } : value == SubscriptionPlan.family ? {
        family: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
